
const mercedesFeatures = [
         "Heated front seats",
         "40/20/40-split folding rear seats",
         "Dual-zone automatic climate control",
         "Power tilt/sliding tinted glass sunroof",
         "Power-folding side mirrors",
         "Power front seats with memory",
         "AMG Performance steering wheel in Nappa leather",
         "Steering wheel with Touch Control Buttons",
         "Illuminated front door sills",
         "Mercedes-Benz User Experience (MBUX)",
         "11.9-inch touchscreen central multimedia display",
         "12.3-inch digital instrument cluster",
         "Biometric authentication",
         "Wireless Apple CarPlay",
         "\"Hey, Mercedes\" keyword activation",
         "FrontBass system",
         "Wireless Android Auto",
         "Bluetooth audio streaming",
         "Hands-free Bluetooth interface",
         "HD Radio receiver",
         "In-car WiFi",
         "USB-C charging port",
         "Over-the-air software updates",
         "Voice Control with Natural Language Understanding",
         "SiriusXM 6-month Platinum Plan trial subscription",
         "Electronic trunk closer",
         "HANDS-FREE ACCESS",
         "Illuminated entry system with logo projectors",
         "KEYLESS-GO",
         "Remote opening and closing of windows and sunroof",
         "Garage door opener",
         "Handcrafted AMG 2.0L inline-4 turbo with hybrid assist",
         "Electric exhaust-gas turbocharger",
         "Hybrid Starter-Generator",
         "AMG SPEEDSHIFT MCT 9-speed transmission",
         "AMG Performance 4MATIC all-wheel drive",
         "AMG DYNAMIC SELECT",
         "AMG DRIVE UNIT",
         "AMG Sport Exhaust System",
         "ECO Start/Stop system",
         "4-wheel multilink suspension",
         "AMG Sport Suspension with AMG RIDE CONTROL",
         "Active rear-wheel steering",
         "AMG Sport Braking System",
         "3-stage AMG parameter steering",
         "ESP Dynamic Cornering Assist",
         "LED headlamps and taillamps",
         "Adaptive Highbeam Assist",
         "LED Daytime Running Lamps",
         "Car-to-X Communication",
         "Mercedes-Benz Emergency Call Service",
         "PRE-SAFE",
         "PRE-SAFE Sound",
         "Active Brake Assist",
         "Rearview camera",
         "Surround View System",
         "PARKTRONIC with Active Parking Assist",
         "Blind Spot Assist with Exit Warning Assist",
         "7 air bags",
         "Brake Assist (BAS)",
         "Electronic Stability Program (ESP)",
         "Adaptive braking technology",
         "SmartKey with KEYLESS-START",
         "Antilock Braking System (ABS)",
         "Antitheft alarm system",
         "GUARD 360° security system",
         "Rain-sensing windshield wipers",
         "Heated washer fluid",
         "Advanced Tire Pressure Monitoring System",
         "4-wheel Electronic Traction System (4-ETS)",
         "Rear side-impact air bags",
         "ATTENTION ASSIST"
];
       
const mercedesFeatures2 = [
         "Power front seats with memory",
         "Heated front seats",
         "40/20/40-split folding rear seats",
         "Dual-zone automatic climate control",
         "Power tilt/sliding tinted glass sunroof",
         "Power-folding side mirrors",
         "AMG Performance steering wheel in Nappa leather",
         "Steering wheel with Touch Control Buttons",
         "Enhanced ambient lighting",
         "Illuminated front door sills",
         "Mercedes-Benz User Experience (MBUX)",
         "11.9-inch touchscreen central multimedia display",
         "12.3-inch digital instrument cluster",
         "Biometric authentication",
         "\"Hey, Mercedes\" keyword activation",
         "Wireless Android Auto",
         "Wireless Apple CarPlay",
         "MB Navigation",
         "MBUX Augmented Video for Navigation",
         "No-charge online navigation map updates for 1 year",
         "1 year of Live Traffic Information",
         "Burmester 3D Surround Sound System",
         "Dolby Atmos",
         "Bluetooth audio streaming",
         "FrontBass system",
         "Hands-free Bluetooth interface",
         "HD Radio receiver",
         "In-car WiFi",
         "USB-C charging port",
         "Over-the-air software updates",
         "Voice Control with Natural Language Understanding",
         "Front-cabin wireless charging with NFC pairing",
         "Online Music Streaming",
         "SiriusXM 6-month Platinum Plan trial subscription",
         "AMG Head-Up Display",
         "Electronic trunk closer",
         "HANDS-FREE ACCESS",
         "Illuminated entry system with logo projectors",
         "KEYLESS-GO",
         "Remote opening and closing of windows and sunroof",
         "Garage door opener",
         "Handcrafted AMG 2.0L inline-4 turbo with hybrid assist",
         "Electric exhaust-gas turbocharger",
         "Hybrid Starter-Generator",
         "AMG SPEEDSHIFT MCT 9-speed transmission",
         "AMG Performance 4MATIC all-wheel drive",
         "AMG DYNAMIC SELECT",
         "AMG DRIVE UNIT",
         "AMG Sport Exhaust System",
         "ECO Start/Stop system",
         "4-wheel multilink suspension",
         "AMG Sport Suspension with AMG RIDE CONTROL",
         "Active rear-wheel steering",
         "AMG Sport Braking System",
         "3-stage AMG parameter steering",
         "ESP Dynamic Cornering Assist",
         "LED headlamps and taillamps",
         "Adaptive Highbeam Assist",
         "LED Daytime Running Lamps",
         "Car-to-X Communication",
         "Mercedes-Benz Emergency Call Service",
         "PRE-SAFE",
         "PRE-SAFE Sound",
         "Active Brake Assist",
         "Rearview camera",
         "Surround View System",
         "PARKTRONIC with Active Parking Assist",
         "Blind Spot Assist with Exit Warning Assist",
         "7 air bags",
         "Brake Assist (BAS)",
         "Electronic Stability Program (ESP)",
         "Adaptive braking technology",
         "SmartKey with KEYLESS-START",
         "Antilock Braking System (ABS)",
         "Antitheft alarm system",
         "GUARD 360° security system",
         "Rain-sensing windshield wipers",
         "Heated washer fluid",
         "Advanced Tire Pressure Monitoring System",
         "4-wheel Electronic Traction System (4-ETS)",
         "Rear side-impact air bags",
         "ATTENTION ASSIST"
];
       

const EQSFeatures1 = [
         "Multicontour front seats with massage",
         "Rapid-heating front seats",
         "Heated steering wheel",
         "Active ambient lighting",
         "Heated power front seats with memory",
         "Ventilated front seats",
         "Heated rear seats",
         "Panorama roof",
         "Dual-zone automatic climate control",
         "Pre-entry climate control",
         "Steering wheel with Touch Control Buttons",
         "AMG Performance steering wheel in Nappa leather",
         "AMG DRIVE UNIT",
         "Rearview camera",
         "12.3-inch digital instrument cluster",
         "12.3-inch OLED front passenger display",
         "MB Navigation with Electric Intelligence",
         "Route-based Speed Adaptation",
         "MBUX Augmented Video for Navigation",
         "No-charge online navigation map updates for 1 year",
         "Over-the-air software updates",
         "MBUX Augmented Reality AMG Head-Up Display",
         "Front-cabin wireless charging",
         "Burmester 3D Surround Sound system w/EV Sound",
         "SiriusXM 6-month Platinum Plan trial subscription",
         "HD Radio receiver",
         "Wireless Apple CarPlay",
         "Wireless Android Auto",
         "Online Music Streaming",
         "Bluetooth audio streaming",
         "Hands-free Bluetooth interface",
         "Six 100W USB-C charging ports",
         "AMG SOUND EXPERIENCE",
         "64-color LED ambient lighting",
         "Illuminated door sills",
         "LED logo projectors",
         "Power-folding side mirrors",
         "KEYLESS-GO with seamless door handles",
         "Electronic liftgate closer",
         "HANDS-FREE ACCESS",
         "Illuminated entry system",
         "Garage door opener",
         "Dual AMG-specific electric motors with boost function",
         "AMG Performance 4MATIC+ all-wheel drive",
         "Intelligent Energy Recovery with paddles",
         "AMG DYNAMIC SELECT",
         "AMG DRIVE UNIT",
         "KEYLESS-GO",
         "Remote opening and closing of windows and sunroof",
         "Garage door opener",
         "Handcrafted AMG 2.0L inline-4 turbo with hybrid assist",
         "Electric exhaust-gas turbocharger",
         "Hybrid Starter-Generator",
         "AMG SPEEDSHIFT MCT 9-speed transmission",
         "AMG Performance 4MATIC all-wheel drive",
         "AMG DYNAMIC SELECT",
         "AMG DRIVE UNIT",
         "AMG Sport Exhaust System",
         "ECO Start/Stop system",
         "4-wheel multilink suspension",
         "AMG Sport Suspension with AMG RIDE CONTROL",
         "Active rear-wheel steering",
         "AMG Sport Braking System",
         "3-stage AMG parameter steering",
         "ESP Dynamic Cornering Assist",
         "AMG DYNAMIC PLUS Package",
         "Advanced 108.4-kWh EV battery",
         "Multiple charging options",
         "AMG RIDE CONTROL+ air suspension",
         "9-degree rear axle steering",
         "AMG high-performance compound brake system",
         "Antitheft alarm system",
         "GUARD 360° security system",
         "Active Brake",
         "Mercedes-Benz Emergency Call",
         "Surround View System",
         "Active Steering Assist",
         "Active Blind Spot Assist",
         "Exit Warning Assist",
         "Active Lane Keeping Assist",
         "SmartKey with KEYLESS-START"
];
       
const EQSFeatures2 = [
         "Heated steering wheel",
         "Active ambient lighting",
         "Multicontour front seats with massage",
         "Rapid-heating front seats",
         "Heated power front seats with memory",
         "Ventilated front seats",
         "Heated rear seats",
         "Panorama roof",
         "Pre-entry climate control",
         "4-zone automatic climate control",
         "Steering wheel with Touch Control Buttons",
         "AMG Performance steering wheel in Nappa leather",
         "AMG DRIVE UNIT",
         "MBUX Hyperscreen",
         "Mercedes-Benz User Experience (MBUX)",
         "\"Hey, Mercedes\" keyword activation",
         "Voice Control with Natural Language Understanding",
         "Biometric authentication",
         "12.3-inch digital instrument cluster",
         "12.3-inch OLED front passenger display",
         "MB Navigation with Electric Intelligence",
         "Route-based Speed Adaptation",
         "MBUX Augmented Video for Navigation",
         "No-charge online navigation map updates for 1 year",
         "Over-the-air software updates",
         "MBUX Augmented Reality AMG Head-Up Display",
         "Front-cabin wireless charging",
         "12.3-inch digital instrument cluster",
         "12.3-inch OLED front passenger display",
         "MB Navigation with Electric Intelligence",
         "Route-based Speed Adaptation",
         "MBUX Augmented Video for Navigation",
         "No-charge online navigation map updates for 1 year",
         "Over-the-air software updates",
         "MBUX Augmented Reality AMG Head-Up Display",
         "Front-cabin wireless charging",
         "Burmester 3D Surround Sound system w/EV Sound",
         "SiriusXM 6-month Platinum Plan trial subscription",
         "HD Radio receiver",
         "Wireless Apple CarPlay",
         "Wireless Android Auto",
         "Online Music Streaming",
         "Bluetooth audio streaming",
         "Hands-free Bluetooth interface",
         "Six 100W USB-C charging ports",
         "AMG SOUND EXPERIENCE",
         "64-color LED ambient lighting",
         "Illuminated door sills",
         "LED logo projectors",
         "Power-folding side mirrors",
         "KEYLESS-GO with seamless door handles",
         "Electronic liftgate closer",
         "HANDS-FREE ACCESS",
         "Hands-free Bluetooth interface",
         "Six 100W USB-C charging ports",
         "AMG SOUND EXPERIENCE",
         "64-color LED ambient lighting",
         "Illuminated door sills",
         "LED logo projectors",
         "Power-folding side mirrors",
         "KEYLESS-GO with seamless door handles",
         "Electronic liftgate closer",
         "HANDS-FREE ACCESS",
         "Illuminated entry system",
         "Garage door opener",
         "Dual AMG-specific electric motors with boost function",
         "AMG Performance 4MATIC+ all-wheel drive",
         "Intelligent Energy Recovery with paddles",
         "AMG DYNAMIC SELECT",
         "AMG DRIVE UNIT",
         "AMG DYNAMIC PLUS Package",
         "Advanced 108.4-kWh EV battery",
         "Multiple charging options",
         "AMG RIDE CONTROL+ air suspension",
         "9-degree rear axle steering",
         "AMG high-performance compound brake system",
         "Car-to-X Communication",
         "PRE-SAFE",
         "PRE-SAFE Sound",
         "PRE-SAFE PLUS",
         "PRE-SAFE Impulse Side",
         "LED DIGITAL LIGHT headlamps w/lightband",
         "Adaptive Highbeam Assist",
         "ATTENTION ASSIST",
         "Active Brake Assist",
         "Mercedes-Benz Emergency Call",
         "Surround View System",
         "PARKTRONIC with Active Parking Assist"
];

const EQSFeatures3 = [
         "Heated steering wheel",
         "Active ambient lighting",
         "Multicontour front seats with massage",
         "Rapid-heating front seats",
         "Heated power front seats with memory",
         "Ventilated front seats",
         "Heated rear seats",
         "Panorama roof",
         "Pre-entry climate control",
         "4-zone automatic climate control",
         "Steering wheel with Touch Control Buttons",
         "AMG Performance steering wheel in Nappa leather",
         "AMG DRIVE UNIT",
         "MBUX Hyperscreen",
         "Mercedes-Benz User Experience (MBUX)",
         "\"Hey, Mercedes\" keyword activation",
         "Voice Control with Natural Language Understanding",
         "Biometric authentication",
         "12.3-inch digital instrument cluster",
         "12.3-inch OLED front passenger display",
         "MB Navigation with Electric Intelligence",
         "Route-based Speed Adaptation",
         "MBUX Augmented Video for Navigation",
         "No-charge online navigation map updates for 1 year",
         "Over-the-air software updates",
         "MBUX Augmented Reality AMG Head-Up Display",
         "Front-cabin wireless charging",
         "Burmester 3D Surround Sound system w/EV Sound",
         "SiriusXM 6-month Platinum Plan trial subscription",
         "HD Radio receiver",
         "Wireless Apple CarPlay",
         "Wireless Android Auto",
         "Online Music Streaming",
         "Bluetooth audio streaming",
         "Voice Control with Natural Language Understanding",
         "Biometric authentication",
         "12.3-inch digital instrument cluster",
         "12.3-inch OLED front passenger display",
         "MB Navigation with Electric Intelligence",
         "Route-based Speed Adaptation",
         "MBUX Augmented Video for Navigation",
         "No-charge online navigation map updates for 1 year",
         "Over-the-air software updates",
         "MBUX Augmented Reality AMG Head-Up Display",
         "Front-cabin wireless charging",
         "Burmester 3D Surround Sound system w/EV Sound",
         "SiriusXM 6-month Platinum Plan trial subscription",
         "HD Radio receiver",
         "Wireless Apple CarPlay",
         "Wireless Android Auto",
         "Online Music Streaming",
         "Bluetooth audio streaming",
         "Hands-free Bluetooth interface",
         "Six 100W USB-C charging ports",
         "AMG SOUND EXPERIENCE",
         "64-color LED ambient lighting",
         "Illuminated door sills",
         "LED logo projectors",
         "Power-folding side mirrors",
         "KEYLESS-GO with seamless door handles",
         "Electronic liftgate closer",
         "HANDS-FREE ACCESS",
         "Hands-free Bluetooth interface",
         "Six 100W USB-C charging ports",
         "AMG SOUND EXPERIENCE",
         "64-color LED ambient lighting",
         "Illuminated door sills",
         "LED logo projectors",
         "Power-folding side mirrors",
         "KEYLESS-GO with seamless door handles",
         "Electronic liftgate closer",
         "HANDS-FREE ACCESS",
         "Illuminated entry system",
         "Garage door opener",
         "Dual AMG-specific electric motors with boost function",
         "AMG Performance 4MATIC+ all-wheel drive",
         "Intelligent Energy Recovery with paddles",
         "AMG DYNAMIC SELECT",
         "AMG DRIVE UNIT",
         "AMG DYNAMIC PLUS Package",
         "Advanced 108.4-kWh EV battery",
         "Multiple charging options",
         "AMG RIDE CONTROL+ air suspension",
         "9-degree rear axle steering",
         "AMG high-performance compound brake system",
         "Car-to-X Communication",
         "PRE-SAFE",
         "PRE-SAFE Sound",
         "PRE-SAFE PLUS",
         "PRE-SAFE Impulse Side",
         "LED DIGITAL LIGHT headlamps w/lightband",
         "Adaptive Highbeam Assist",
         "ATTENTION ASSIST",
         "Active Brake Assist",
         "Mercedes-Benz Emergency Call",
         "Surround View System",
         "PARKTRONIC with Active Parking Assist"
];

const maybachFeatures1 = [
         "Heated front seats",
         "40/20/40-split folding rear seats",
         "Dual-zone automatic climate control",
         "Power tilt/sliding tinted glass sunroof",
         "Power-folding side mirrors",
         "Power front seats with memory",
         "AMG Performance steering wheel in Nappa leather",
         "Steering wheel with Touch Control Buttons",
         "Illuminated front door sills",
         "Mercedes-Benz User Experience (MBUX)",
         "11.9-inch touchscreen central multimedia display",
         "12.3-inch digital instrument cluster",
         "Biometric authentication",
         "Wireless Apple CarPlay",
         "\"Hey, Mercedes\" keyword activation",
         "FrontBass system",
         "Wireless Android Auto",
         "Bluetooth audio streaming",
         "Hands-free Bluetooth interface",
         "HD Radio receiver",
         "In-car WiFi",
         "USB-C charging port",
         "Over-the-air software updates",
         "Voice Control with Natural Language Understanding",
         "SiriusXM 6-month Platinum Plan trial subscription",
         "Electronic trunk closer",
         "HANDS-FREE ACCESS",
         "Illuminated entry system with logo projectors",
         "KEYLESS-GO",
         "Remote opening and closing of windows and sunroof",
         "Garage door opener",
         "Handcrafted AMG 2.0L inline-4 turbo with hybrid assist",
         "Electric exhaust-gas turbocharger",
         "Hybrid Starter-Generator",
         "AMG SPEEDSHIFT MCT 9-speed transmission",
         "AMG Performance 4MATIC all-wheel drive",
         "AMG DYNAMIC SELECT",
         "AMG DRIVE UNIT",
         "AMG Sport Exhaust System",
         "ECO Start/Stop system",
         "4-wheel multilink suspension",
         "AMG Sport Suspension with AMG RIDE CONTROL",
         "Active rear-wheel steering",
         "AMG Sport Braking System",
         "3-stage AMG parameter steering",
         "ESP Dynamic Cornering Assist",
         "LED headlamps and taillamps",
         "Adaptive Highbeam Assist",
         "LED Daytime Running Lamps",
         "Car-to-X Communication",
         "Mercedes-Benz Emergency Call Service",
         "PRE-SAFE",
         "PRE-SAFE Sound",
         "Active Brake Assist",
         "Rearview camera",
         "Surround View System",
         "PARKTRONIC with Active Parking Assist",
         "Blind Spot Assist with Exit Warning Assist",
         "7 air bags",
         "Brake Assist (BAS)",
         "Electronic Stability Program (ESP)",
         "Adaptive braking technology",
         "SmartKey with KEYLESS-START",
         "Antilock Braking System (ABS)",
         "Antitheft alarm system",
         "GUARD 360° security system",
         "Rain-sensing windshield wipers",
         "Heated washer fluid",
         "Advanced Tire Pressure Monitoring System",
         "4-wheel Electronic Traction System (4-ETS)",
         "Rear side-impact air bags",
         "ATTENTION ASSIST"
];
    
const maybachFeatures2 = [
         "Heated steering wheel",
         "Active ambient lighting",
         "Multicontour front seats with massage",
         "Rapid-heating front seats",
         "Heated power front seats with memory",
         "Ventilated front seats",
         "Heated rear seats",
         "Panorama roof",
         "Pre-entry climate control",
         "4-zone automatic climate control",
         "Steering wheel with Touch Control Buttons",
         "AMG Performance steering wheel in Nappa leather",
         "AMG DRIVE UNIT",
         "MBUX Hyperscreen",
         "Mercedes-Benz User Experience (MBUX)",
         "\"Hey, Mercedes\" keyword activation",
         "Voice Control with Natural Language Understanding",
         "Biometric authentication",
         "12.3-inch digital instrument cluster",
         "12.3-inch OLED front passenger display",
         "MB Navigation with Electric Intelligence",
         "Route-based Speed Adaptation",
         "MBUX Augmented Video for Navigation",
         "No-charge online navigation map updates for 1 year",
         "Over-the-air software updates",
         "MBUX Augmented Reality AMG Head-Up Display",
         "Front-cabin wireless charging",
         "12.3-inch digital instrument cluster",
         "12.3-inch OLED front passenger display",
         "MB Navigation with Electric Intelligence",
         "Route-based Speed Adaptation",
         "MBUX Augmented Video for Navigation",
         "No-charge online navigation map updates for 1 year",
         "Over-the-air software updates",
         "MBUX Augmented Reality AMG Head-Up Display",
         "Front-cabin wireless charging",
         "Burmester 3D Surround Sound system w/EV Sound",
         "SiriusXM 6-month Platinum Plan trial subscription",
         "HD Radio receiver",
         "Wireless Apple CarPlay",
         "Wireless Android Auto",
         "Online Music Streaming",
         "Bluetooth audio streaming",
         "Hands-free Bluetooth interface",
         "Six 100W USB-C charging ports",
         "AMG SOUND EXPERIENCE",
         "64-color LED ambient lighting",
         "Illuminated door sills",
         "LED logo projectors",
         "Power-folding side mirrors",
         "KEYLESS-GO with seamless door handles",
         "Electronic liftgate closer",
         "HANDS-FREE ACCESS",
         "Hands-free Bluetooth interface",
         "Six 100W USB-C charging ports",
         "AMG SOUND EXPERIENCE",
         "64-color LED ambient lighting",
         "Illuminated door sills",
         "LED logo projectors",
         "Power-folding side mirrors",
         "KEYLESS-GO with seamless door handles",
         "Electronic liftgate closer",
         "HANDS-FREE ACCESS",
         "Illuminated entry system",
         "Garage door opener",
         "Dual AMG-specific electric motors with boost function",
         "AMG Performance 4MATIC+ all-wheel drive",
         "Intelligent Energy Recovery with paddles",
         "AMG DYNAMIC SELECT",
         "AMG DRIVE UNIT",
         "AMG DYNAMIC PLUS Package",
         "Advanced 108.4-kWh EV battery",
         "Multiple charging options",
         "AMG RIDE CONTROL+ air suspension",
         "9-degree rear axle steering",
         "AMG high-performance compound brake system",
         "Car-to-X Communication",
         "PRE-SAFE",
         "PRE-SAFE Sound",
         "PRE-SAFE PLUS",
         "PRE-SAFE Impulse Side",
         "LED DIGITAL LIGHT headlamps w/lightband",
         "Adaptive Highbeam Assist",
         "ATTENTION ASSIST",
         "Active Brake Assist",
         "Mercedes-Benz Emergency Call",
         "Surround View System",
         "PARKTRONIC with Active Parking Assist"
];

const maybachFeatures3 = [
         "Heated steering wheel",
         "Active ambient lighting",
         "Multicontour front seats with massage",
         "Rapid-heating front seats",
         "Heated power front seats with memory",
         "Ventilated front seats",
         "Heated rear seats",
         "Panorama roof",
         "Pre-entry climate control",
         "4-zone automatic climate control",
         "Steering wheel with Touch Control Buttons",
         "AMG Performance steering wheel in Nappa leather",
         "AMG DRIVE UNIT",
         "MBUX Hyperscreen",
         "Mercedes-Benz User Experience (MBUX)",
         "\"Hey, Mercedes\" keyword activation",
         "Voice Control with Natural Language Understanding",
         "Biometric authentication",
         "12.3-inch digital instrument cluster",
         "12.3-inch OLED front passenger display",
         "MB Navigation with Electric Intelligence",
         "Route-based Speed Adaptation",
         "MBUX Augmented Video for Navigation",
         "No-charge online navigation map updates for 1 year",
         "Over-the-air software updates",
         "MBUX Augmented Reality AMG Head-Up Display",
         "Front-cabin wireless charging",
         "Burmester 3D Surround Sound system w/EV Sound",
         "SiriusXM 6-month Platinum Plan trial subscription",
         "HD Radio receiver",
         "Wireless Apple CarPlay",
         "Wireless Android Auto",
         "Online Music Streaming",
         "Bluetooth audio streaming",
         "Voice Control with Natural Language Understanding",
         "Biometric authentication",
         "12.3-inch digital instrument cluster",
         "12.3-inch OLED front passenger display",
         "MB Navigation with Electric Intelligence",
         "Route-based Speed Adaptation",
         "MBUX Augmented Video for Navigation",
         "No-charge online navigation map updates for 1 year",
         "Over-the-air software updates",
         "MBUX Augmented Reality AMG Head-Up Display",
         "Front-cabin wireless charging",
         "Burmester 3D Surround Sound system w/EV Sound",
         "SiriusXM 6-month Platinum Plan trial subscription",
         "HD Radio receiver",
         "Wireless Apple CarPlay",
         "Wireless Android Auto",
         "Online Music Streaming",
         "Bluetooth audio streaming",
         "Hands-free Bluetooth interface",
         "Six 100W USB-C charging ports",
         "AMG SOUND EXPERIENCE",
         "64-color LED ambient lighting",
         "Illuminated door sills",
         "LED logo projectors",
         "Power-folding side mirrors",
         "KEYLESS-GO with seamless door handles",
         "Electronic liftgate closer",
         "HANDS-FREE ACCESS",
         "Hands-free Bluetooth interface",
         "Six 100W USB-C charging ports",
         "AMG SOUND EXPERIENCE",
         "64-color LED ambient lighting",
         "Illuminated door sills",
         "LED logo projectors",
         "Power-folding side mirrors",
         "KEYLESS-GO with seamless door handles",
         "Electronic liftgate closer",
         "HANDS-FREE ACCESS",
         "Illuminated entry system",
         "Garage door opener",
         "Dual AMG-specific electric motors with boost function",
         "AMG Performance 4MATIC+ all-wheel drive",
         "Intelligent Energy Recovery with paddles",
         "AMG DYNAMIC SELECT",
         "AMG DRIVE UNIT",
         "AMG DYNAMIC PLUS Package",
         "Advanced 108.4-kWh EV battery",
         "Multiple charging options",
         "AMG RIDE CONTROL+ air suspension",
         "9-degree rear axle steering",
         "AMG high-performance compound brake system",
         "Car-to-X Communication",
         "PRE-SAFE",
         "PRE-SAFE Sound",
         "PRE-SAFE PLUS",
         "PRE-SAFE Impulse Side",
         "LED DIGITAL LIGHT headlamps w/lightband",
         "Adaptive Highbeam Assist",
         "ATTENTION ASSIST",
         "Active Brake Assist",
         "Mercedes-Benz Emergency Call",
         "Surround View System",
         "PARKTRONIC with Active Parking Assist"
];
       
       
   
export { mercedesFeatures, mercedesFeatures2, EQSFeatures1, EQSFeatures2, EQSFeatures3, maybachFeatures1, maybachFeatures2, maybachFeatures3 }       